<?php
// $Id$

/**
 * @file
 */

/**
 * Implementation of hook_menu_alter().
 */
function jrst_custom_menu_alter(&$items) {
  $items['user/%user/view']['type'] = MENU_LOCAL_TASK;
  $items['user/%user/track']['type'] = MENU_CALLBACK;
}

/**
 * Implementation of hook_block().
 */
function jrst_custom_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['follow_block'] = array(
        'info' => t('Follow/Unfollow Block'),
        'cache' => BLOCK_NO_CACHE,
      );
      $blocks['import_now'] = array(
        'info' => t('JRST: Import Now'),
        'cache' => BLOCK_CACHE_PER_ROLE,
      );
      $blocks['author_center'] = array(
        'info' => t('JRST: Author Center'),
        'cache' => BLOCK_NO_CACHE,
      );
      $blocks['link_to_profile'] = array(
        'info' => t('JRST: Link to Profile (For Dashboard)'),
        'cache' => BLOCK_NO_CACHE,
      );
      $blocks['update_user_reference'] = array(
        'info' => t('JRST: Article User Reference'),
        'cache' => BLOCK_NO_CACHE,
      );
      $blocks['jrst_user_login'] = array(
        'info' => t('JRST: User Login Text'),
        'cache' => BLOCK_NO_CACHE,
      );

      return $blocks;
    case 'view':
      global $user;
      $block = array();
      switch ($delta) {
        case 'follow_block':
          $output = '<div class="jrst-notification-follow">';
          $output .= flag_create_link('follow', arg(1));
          $output .= '</div>';
          $block['content'] = $output;
          break;
        case 'import_now':
          $block['subject'] = t('Import Now');
          $block['content'] = l(t('Import Now From Manuscript Central'), 'import/mail_impor');
          break;
        case 'link_to_profile':
          $block['subject'] = t('My Profile');
          $block['content'] = l(t('Go to my profile'), 'user');
          break;
        case 'jrst_user_login':
          if ($user->uid == 0) {
            $block['content'] = l('Login', 'user/login', array('query' => drupal_get_destination())) .
          ' / ' . l('Register', 'user/register');
          }
          break;
        case 'author_center':
          global $user;
          if (arg(0) == 'node' && is_numeric(arg(1))) {
            $node = node_load(arg(1));
            if ($node->type == 'article' && $node->field_article_author[0]['uid'] == $user->uid || user_access('administer nodes')) {
              $podcast = db_result(db_query('SELECT nid FROM {content_type_podcast} WHERE field_podcast_article_nid = %d', $node->nid));

              if (!is_numeric($podcast)) {
                $links[] = '<a href="/node/add/podcast/' . $node->nid . '">Upload a Podcast</a>';
              }
              else {
                $links[] = '<a href="/node/' . $podcast . '">View Podcast</a>';
              }

              $document = db_result(db_query('SELECT nid FROM {content_type_document} WHERE field_document_article_nid = %d', $node->nid));

              $text = t('Upload additional Documents');
              if (!is_numeric($document)) {
                $links[] = '<a href="/node/add/document/' . $node->nid . '">' . $text . '</a>';
              }
              else {
                $links[] = '<a href="/node/' . $document . '">' . $text .'</a>';
              }
              $block['subject'] = t('Authors Tools');
              $block['content'] = theme('item_list', $links);
            }
          }
          break;
      }
      return $block;
  }
}

/**
 * Implementation of hook_field_formatter_info(),.
 */
function jrst_custom_field_formatter_info() {
  return array(
    'jrst_custom_wiley_link' => array(
      'label' => t('Wiley Link'),
      'field types' => array('text'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
  );
}
/**
 * Implementation of hook_theme().
 */
function jrst_custom_theme() {
  return array(
    'jrst_custom_formatter_jrst_custom_wiley_link' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

function theme_jrst_custom_formatter_jrst_custom_wiley_link($element) {
  $wiley_id = $element['#item']['value'];
  if (isset($wiley_id)) {
    $wiley_id = strtolower($wiley_id);
    $wiley_id = substr_replace($wiley_id , ".", 3, 0);
    $link = 'http://onlinelibrary.wiley.com/doi/10.1002/' . $wiley_id . '/abstract';
    return l(t('Link to Wiley - @value', array('@value' => $element['#item']['value'])), $link, array('attributes' => array('target' => '_blank')));
  }
}


/**
 * Implementation of hook_flag_default_flags().
 */
function jrst_custom_flag_default_flags() {
  $flags = array();
  $flags[] = array(
    'content_type' => 'node',
    'name' => 'follow',
    'title' => 'Follow/Unfollow',
    'roles' => array(2),
    'global' => FALSE,
    'types' => array('article', 'blog', 'discussion', 'group', 'wiki'),
    'flag_short' => 'Follow',
    'flag_long' => 'Follow',
    'flag_message' => '',
    'unflag_short' => 'Following',
    'unflag_long' => 'Unfollow',
    'unflag_message' => '',
    'show_on_page' => FALSE,
    'show_on_teaser' => FALSE,
    'show_on_form' => FALSE,
    'status' => TRUE,
    'locked' => array('show_on_teaser', 'name', 'global'),
  );
  return $flags;
}
/**
 * Function that will eventually allow one time links for "approve/deny" responses
 * MORE DOCUMENTATION TO COME LATER!!!
 * FUNCTION IS NOT COMPLETE!!!!
 */
function jrst_custom_userref_response($nid, $uid, $field, $timestamp, $hashed_password, $value = NULL) {
  global $user;
  // If user isn't logged in, they need to be
  if (!$user->uid) {
    drupal_set_message(t('You must log in before responding to your assignment'));
    drupal_goto( 'user/login',drupal_get_destination() );
  }
  else if ($user->uid != $uid) {
    drupal_set_message(t('This acceptance link is for a different user, this error has been logged'), 'warning');
    watchdog(
      'jrst_custom_userref',
      '@uid tried to accept/deny a user reference for @nid with link for someone else',
      array('@uid' => $user->uid, '@nid' => $nid)
    );
    drupal_goto();
  }
  $node = node_load($nid);
  // Make sure node still exists
  if ($node->nid) {
    // @todo Completed this check
    $field = content_fields($field, $node->type);
    // Check that field is of type user reference, just to be sure
    // someone doesn't get lucky
  }

}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Defines custom plugins for feed tamper, pulling them into this module
 */
function jrst_custom_ctools_plugin_directory($module, $plugin) {
  if ($module == 'feeds_tamper') {
    return 'plugins';
  }
  else if ($module == 'mailhandler' && $plugin == 'commands_plugin') {
    return 'plugins/MailhandlerCommands';
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * Removes text from e-mail address in form that tells user how the email address will be private.
 * Make sure the taxonomy form in the group is not in a vertical tab
 */
function jrst_custom_form_alter(&$form, &$form_state, $form_id) {
  // Disable vertical tabs on a form.
  $vtabs = variable_get('vertical_tabs_forms', array());
  $vtabs['project_issue_node_form'] = FALSE;
  variable_set('vertical_tabs_forms', $vtabs);

  switch ($form_id) {
    // Change the description for the email address field here to something more appropriate.
    case 'user_profile_form':
    case 'user_register':
      $form['account']['mail']['#description'] = t('A valid e-mail address. All e-mails will be sent to this address');
      break;
    // Make sure the taxonomy fieldset on nodes do not appear in a vertical tab
    case 'group_node_form':
      $form['taxonomy']['#group'] = FALSE;
      break;
  }
}

/**
 * Implementation of hook_link_alter().
 *
 * Remove user_name blog link from blog entries
 */
function jrst_custom_link_alter(&$links, $node, $comment = NULL) {
  if ($node->type == 'blog') {
    unset($links['blog_usernames_blog']);
  }
}

/**
 * Implementation of hook_link().
 *
 * Defines "create new" node link. This link appears on all node pages, except issues,
 * and allows users to "create a new <node_type>" by clicking the link
 */
function jrst_custom_link($type, $object, $teaser = FALSE) {
  if ($type == 'node' && !$teaser && $object->type != 'issue' && user_access('create ' . $object->type . ' content')) {
    if (empty($object->og_groups)) {
      $links['add_new_content'] = array(
        'title' => t('Create New @type', array('@type' => $object->type)),
        'href' => 'node/add/' . $object->type,
      );
    }
    else {
      $links['add_new_content'] = array(
        'title' => t('Create New @type', array('@type' => $object->type)),
        'href' => 'node/add/' . $object->type,
        'query' => 'gids[0]=' . implode('+', $object->og_groups),
      );
      
    }
  }
  return $links;
}

/**
 * Implements hook_feeds_node_processor_targets_alter().
 * 
 * Allows the workflow state to be set by a field coming from a mail handler
 */
function jrst_custom_feeds_node_processor_targets_alter(&$targets, $content_type) {
  if ($content_type == 'article') {
    $targets['workflow_state'] = array(
      'name' => t('Workflow State (JRST ONLY)'),
      'description' => t('What editorial state the node is in'),
      'callback' => 'jrst_custom_workflow_feeds_set_target_sid',
    );
  }
}

/*
 * Callback for jrst_custom_feeds_node_processor_targets_alter
 * 
 * Defines custom callback for workflow setting for JRST. Note, workflow based on sid
 * (dumb), so very specific to this site.
 */
function jrst_custom_workflow_feeds_set_target_sid($node, $key, $keyword) {
  // get possible sid values for this node or Return error
  $keyword = strtolower($keyword);
  if (!(strpos($keyword, 'editorial') === FALSE)) {
    $sid = 8;
  }
  else if (!(strpos($keyword, 'review') === FALSE)) {
    $sid = 9;
  }
  else if (!(strpos($keyword, 'withdraw') === FALSE)) {
    $sid = 12;
  }
  else {
    watchdog('jrst_custom', 'Given bad argument @arg for auto workflow assignment', array('@arg' => $keyword));
    return;
  }

  $sids = array();
  $result = db_query("SELECT sid FROM {workflow_states} ws JOIN {workflow_type_map} wtm ON ws.wid = wtm.wid WHERE wtm.type = '%s'", $node->type);
  while ($state = db_fetch_object($result)) {
    $sids[] = $state->sid;
  }

  // make sure this state is allowed for this node before updating
  if (in_array($sid, $sids)) {
    $node->workflow = $sid;
  }
}

/**
 * Implementation of hook_workflow().
 */
function jrst_custom_workflow($op, $old_state, $new_state, $node) {
  switch ($op) {
    case 'transition post':
      if ($new_state == 11 && $old_state != $new_state && $node->comment != COMMENT_NODE_DISABLED) {
        $node->comment = COMMENT_NODE_DISABLED;
        node_save($node);
      }
  }
}

