<?php
// $Id$

/**
 * @file
 */

/**
 * Implementation of hook_menu().
 *
 * Provides a one time link for denying user reference
 * Highly based on user module one time login
 */
/**
function jrst_custom_menu() {
  // Args, nid, timestamp, hashed password (salted),
  // password_hash a security flaw?
  $items['userref_response/%/%/%/%/%'] = array(
    'title' => 'Request Response',
    'page callback' => 'jrst_custom_userref_response',
    'page arguments' => array(1,2,3,4),
    'access callback' => TRUE,
  );

  return $items;
}
 */

/**
 * Implementation of hook_block().
 */
function jrst_custom_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['follow_block'] = array(
        'info' => t('Follow/Unfollow Block'),
        'cache' => BLOCK_NO_CACHE,
      );
      $blocks['import_now'] = array(
        'info' => t('JRST: Import Now'),
        'cache' => BLOCK_CACHE_PER_ROLE,
      );

      return $blocks;
    case 'view':
      switch ($delta) {
        case 'follow_block':
          $output = '<div class="jrst-notification-follow">';
          $output .= flag_create_link('follow', arg(1));
          $output .= '</div>';
          $block['content'] = $output;
          break;
        case 'import_now':
          $block['content'] = l(t('Import Now'), 'import/mail_impor');
          $block['subject'] = t('Import Now');

          break;
        return $block;
      }
  }
}

/**
 * Implementation of hook_flag_default_flags().
 */
function jrst_custom_flag_default_flags() {
  $flags = array();
  $flags[] = array(
    'content_type' => 'node',
    'name' => 'follow',
    'title' => 'Follow/Unfollow',
    'roles' => array(2),
    'global' => FALSE,
    'types' => array('article', 'blog', 'discussion', 'group', 'wiki'),
    'flag_short' => 'Follow',
    'flag_long' => 'Follow',
    'flag_message' => '',
    'unflag_short' => 'Following',
    'unflag_long' => 'Unfollow',
    'unflag_message' => '',
    'show_on_page' => FALSE,
    'show_on_teaser' => FALSE,
    'show_on_form' => FALSE,
    'status' => TRUE,
    'locked' => array('show_on_teaser', 'name', 'global'),
  );
  return $flags;
}

function jrst_custom_userref_response($nid, $uid, $field, $timestamp, $hashed_password, $value = NULL) {
  global $user;
  // If user isn't logged in, they need to be
  if (!$user->uid) {
    drupal_set_message(t('You must log in before responding to your assignment'));
    drupal_goto( 'user/login',drupal_get_destination() );
  }
  else if ($user->uid != $uid) {
    drupal_set_message(t('This acceptance link is for a different user, this error has been logged'), 'warning');
    watchdog(
      'jrst_custom_userref',
      '@uid tried to accept/deny a user reference for @nid with link for someone else',
      array('@uid' => $user->uid, '@nid' => $nid)
    );
    drupal_goto();
  }
  $node = node_load($nid);
  // Make sure node still exists
  if ($node->nid) {
    // @todo Completed this check
    $field = content_fields($field, $node->type);
    // Check that field is of type user reference, just to be sure
    // someone doesn't get lucky
  }

}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Defines custom plugins for feed tamper, pulling them into this module
 */
function jrst_custom_ctools_plugin_directory($module, $plugin) {
  if ($module == 'feeds_tamper') {
    return 'plugins';
  }
  else if ($module == 'mailhandler' && $plugin == 'commands_plugin') {
    return 'plugins/MailhandlerCommands';
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * Removes text from e-mail address in form that tells user how the email address will be private.
 * Make sure the taxonomy form in the group is not in a vertical tab
 */
function jrst_custom_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_profile_form':
    case 'user_register':
      $form['account']['mail']['#description'] = t('A valid e-mail address. All e-mails will be sent to this address');
      break;
    case 'group_node_form':
      $form['taxonomy']['#group'] = FALSE;
      break;
    case 'article_node_form':
      array_unshift($form['#validate'], 'jrst_custom_quick_hack');
      array_unshift($form['#submit'], 'jrst_custom_quick_hack');
      break;

  }
}

/**
 * Terrible, terrible quick hack. Comment driven, during some point, changes this value to a
 * boolean. (Can't find where though, so of a gun, spent 3 hours or so, finally just posted a
 * bug. Needs to be fixed.
 *
 * @todo - Fix comment_driven so that we don't need this.
 */
function jrst_custom_quick_hack($form, &$form_state) {
  $form_state['values']['field_article_resubmit'][0]['value'] = (int) $form_state['values']['field_article_resubmit'][0]['value'];
}


/**
 * Implementation of hook_link_alter().
 *
 * Remove user_name blog link from blog entries
 */
function jrst_custom_link_alter(&$links, $node, $comment = NULL) {
  if ($node->type == 'blog') {
    unset($links['blog_usernames_blog']);
  }
}

/**
 * Implementation of hook_link().
 *
 * Defines "create new" node link
 */
function jrst_custom_link($type, $object, $teaser = FALSE) {
  if ($type == 'node' && !$teaser && user_access('create ' . $object->type . ' content')) {
    if (empty($object->og_groups)) {
      $links['add_new_content'] = array(
        'title' => t('Create New @type', array('@type' => $object->type)),
        'href' => 'node/add/' . $object->type,
      );
    }
    else {
      $links['add_new_content'] = array(
        'title' => t('Create New @type', array('@type' => $object->type)),
        'href' => 'node/add/' . $object->type,
        'query' => 'gids[0]=' . implode('+', $object->og_groups),
      );
      
    }
  }
  return $links;
}
