<?php
// $Id$

/**
 * @file
 */

/**
 * Implementation of hook_menu().
 */
function jrst_app_menu() {
  $items['js/jrst-app/get/position'] = array(
    'page callback' => 'jrst_app_get_position_ajax',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function jrst_app_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'application_node_form') {
    $form['buttons']['submit']['#submit'][] = 'jrst_app_node_form_submit';
  }
}

function jrst_app_node_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'dashboard';
}


/**
 * Implementation of hook_menu_alter().
 */
function jrst_app_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  global $user;
  if (($op == 'prepare' || $op == 'validate') && $node->type == 'application') {
    if ($node->nid == 0 && $nnid = jrst_app_user_existing($node->type)) {
      drupal_set_message(t('You may only have one application, please edit your old application'));
      drupal_goto('node/' . $nnid . '/edit');
    }
  }
  if ($op == 'update' || $op == 'insert') {
    drupal_set_message(t('Your Application has been saved, thank you for applying.'));
  }
  if ($op == 'view' && $node->uid == $user->uid && !user_access('administer nodes')) {
    drupal_goto('node/' . $node->nid . '/edit');
  }
}
function jrst_app_user_existing($type) {
  global $user;
  if (user_access('administer nodes')) {
    return FALSE;
  }
  $sql = 'SELECT nid FROM {node} WHERE type = "%s" AND uid = %d';
  $result = db_result(db_query($sql, $type, $user->uid));
  return isset($result) ? $result : FALSE;
}

function jrst_app_get_position_ajax($nid) {
  $args = array($nid);
  $view = views_embed_view('jrst_app_pos_info', 'default', $nid);
  return drupal_json(array('jrst_app_view' => $view));
}

/*
 * Implementation of hook_theme().
 */
function jrst_app_theme() {
  return array(
    'jrst_app_javascript' => array(
      'arguments' => array(),
    ),
  );
}

function jrst_app_init() {
  theme('jrst_app_javascript');
}

function theme_jrst_app_javascript() {
  drupal_add_js(drupal_get_path('module', 'jrst_app') . '/jrst_app.js');
  drupal_add_css(drupal_get_path('module', 'jrst_app') . '/jrst_app.css');
}